# This is a basic workflow to help you get started with Actions

name: Data updater

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  #push:
  #  branches: [ daily_update ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      # Rebase from development
      #- name: Rebase from development
      #  run: |
      #    git config user.name "Daily update action"
      #    git config user.email "kito@itosoft.com"
      #    git fetch
      #    git checkout -b development origin/development
      #    git checkout daily_update
      #    git rebase development
      #    git push -u origin

      # Create a branch
      #- name: Create Branch
      #  id: create_branch
      #  env:
      #    TZ: 'Asia/Tokyo'
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #    DATE=`date +"%Y%m%d"`
      #    BRANCH_NAME="daily_update_$DATE"
      #    git checkout -b "$BRANCH_NAME"
      #    echo ::set-output name=branch_name::$BRANCH_NAME

      # Update data
      - name: Update data
        run: |
          cd tool/ruby
          bundle
          rake
          cd ../../

      # Commit and push
      #- name: Push
      #  env:
      #    TZ: 'Asia/Tokyo'
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
      #  run: |
      #    DATE=`date +"%Y-%m-%d"`
      #    git config user.name "Daily update action"
      #    git config user.email "kito@itosoft.com"
      #    git commit -m "Daily update : $DATE" -a
      #    git push --set-upstream origin $BRANCH_NAME

      # Create its pull-request
      - name: Create Pull Request
        env:
          TZ: 'Asia/Tokyo'
        id: cpr
        uses: peter-evans/create-pull-request@v3
        branch: "create-pull-request/daily_update"
        commit-message: "[Daily update]"
        title: "[Daily update]"

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      
      #- name: Create Pull Request
      #  uses: peter-evans/create-pull-request@v3
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    title: 'Daily update'
      #    delete-branch: true
      #    #base: development
      #    body: >
      #      This PR is auto-generated by the data_update action.
