name: Data updater

on:
  schedule:
    - cron: '0 0,9 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out development branch
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      # Scraping data
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X PUT https://covid19-data-akita.herokuapp.com/update

      # Update data.json
      - name: Update data
        run: |
          cd tool/ruby
          bundle
          rake
          cd ../../

      # prepare veriables
      - name: Prepare variables
        id: prepare_variables
        env:
          TZ: 'Asia/Tokyo'
        run: |
          DATE=`date +"%Y/%m/%d"`
          echo "::set-output name=date::$DATE"

      # Create its pull-request
      - name: Create Pull Request
        env:
          TZ: 'Asia/Tokyo'
          DATE: ${{ steps.prepare_variables.outputs.date }}
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: create-pull-request/daily_update
          commit-message: "[Daily update]: ${{$DATE}}"
          title: "[Daily update]: ${{$DATE}}"

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
