# This is a basic workflow to help you get started with Actions

name: Data updater

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  #push:
  #  branches: [ daily_update ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: daily_update
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      # Install the hub command
      - name: install hub
        uses: geertvdc/setup-hub@master

      # Rebase from development
      - name: Rebase from development
        run: |
          git config user.name "Daily update action"
          git config user.email "kito@itosoft.com"
          git fetch
          git rebase origin/development
          git push -u origin

      # Update data.json
      - name: Run a updater data.json
        run: |
          cd tool/ruby
          bundle
          rake
          cd ../../

      # Commit data.json
      - name: Commit to development
        run: |
          git config user.name "Daily update action"
          git config user.email "kito@itosoft.com"
          git commit -m "daily update!" -a
          git push -u origin

      # Create its pull-request
      # @see https://www.ritolab.com/entry/206#aj_3
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y/%m/%d"`
          hub pull-request -m "Daily update $DATE" -b origin:master -h origin:daily_update
          
