name: Pass a pull request for a daily updater to master.
on:
  pull_request:
    branches:
      - development
    types: [closed]

  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, "[Daily update]")

    steps:
      # Create a pull-request
      - name: Create Pull Request
        env:
          TZ: 'Asia/Tokyo'
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: development
          base: master
          title: ${{ github.event.pull_request.title }}

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
